### ISSUE TITLE
It seems to not be working on Process Activity Dialog

### ISSUE THREAD

**Issue by richieri** [reneeb/otrs-DynamicFieldOTRSDBTable#1]
Hi,

I'm trying to add those fields in process activity dialogs but it seems to not be working in there. I can only see values in the fields at common screens such as AgentTicketPhone.

No errors appears in my Event Log :/

**Comment by reneeb** [comment]
Is the field a dynamic field for tickets or articles? It needs to be one for tickets...

**Comment by richieri** [comment]
It's for tickets.

Em qua, 9 de set de 2020 03:45, Renee <notifications@github.com> escreveu:

**Comment by reneeb** [comment]
can you give some details about *what exactly* does not work?

Currently it's a "works on my machine", so I need more details. Is the field in the list of "available fields"? Can you drag'n'drop the field into your activity dialog? Is it shown in the form when you open the activity dialog? Are the values shown in the dropdown? Are the selected value(s) stored?

**Comment by richieri** [comment]
Dear @reneeb ,

Sorry, it may be something wrong with my system. I'll try to reproduce in a fresh new system. If I can reproduce, than I create the Issue again.

Thanks :)
